### ISSUE TITLE
Support embedded JSON

### ISSUE THREAD

**Issue by jamescrowley** [Azure/azapi-vscode#29]
## Versions

This feature does not yet exist in:
 - [ ] the **latest** version of the extension (below)
 - [ ] the **latest** version of the language server (below)

### Extension
```
v0.3.0
```

### Language Server
```
? can't find this from the instructions "the first few lines of relevant Output pane: View -> Output -> terraform-ls"
```

## Problem Statement

We find it useful to define azapi_resource with actual JSON, rather than converting to terraform objects, like so:

```
resource "azapi_resource" "datastore-bronze" {
  type      = "Microsoft.MachineLearningServices/workspaces/datastores@2021-03-01-preview"
  name      = "aml_data_bronze"
  parent_id = azurerm_machine_learning_workspace.aml.id

  body = jsonencode({
    "properties": {
      "contents": {
        ....
      }
    }
  })
}
```

Note the above syntax is valid and passes the providers own validation. 

However, the extension currently can't 'see' properties/contents etc - you have to rewrite to properties = { ... contents = { } } and so on for the validation to be applied. 

## Expected User Experience

The same validation behaviour regardless of how the JSON object is defined within the jsonencode parameter. That would be awesome :)

**Comment by ms-henglu** [comment]
Hi @jamescrowley ,

Thank you for opening this issue.

Yes, terraform supports different syntax to define an HCL object, I'll add support for this syntax.

And there's a workaround for this, you can use [heredoc string](https://www.terraform.io/language/expressions/strings#heredoc-strings) to define JSON object, and the extension will not validate on heredoc, so you can get rid of the red squiggly. 

```hcl
resource "azapi_resource" "datastore-bronze" {
  type      = "Microsoft.MachineLearningServices/workspaces/datastores@2021-03-01-preview"
  name      = "aml_data_bronze"
  parent_id = azurerm_machine_learning_workspace.aml.id

  body = <<JSON
{
    "properties": {
      "contents": {
        ....
      }
    }
  }
JSON
}
```

**Comment by jamescrowley** [comment]
thanks @ms-henglu, you are everywhere! ;)

**Comment by ms-henglu** [comment]
I'll close this issue as it's resolved, but feel free to reopen it if there's any question.
