### ISSUE TITLE
Validate and provide hint for parent_id property.

### ISSUE THREAD

**Issue by grayzu** [Azure/azapi-vscode#32]

**Comment by grayzu** [comment]
@ms-henglu 
Is this something that we can get from the swagger data to make it easier for customers to know what they should be targeting for a given resource?

**Comment by ms-henglu** [comment]
Hi @grayzu ,

This feature is already supported, you can hover on the `parent_id`, it can give a hint like the following image:
<img width="839" alt="image" src="https://user-images.githubusercontent.com/79895375/181665809-4acf408b-3a35-429e-bcf9-9387e33dd3b3.png">

**Comment by grayzu** [comment]
@ms-henglu Awesome! Do we / can we do validation on this as well? i.e. fail plan if the type is incorrect?

**Comment by ms-henglu** [comment]
@grayzu - Yes, we have the validation as well, it'll tell the users the expected id type.
